//! The printer preset library CYM ships, and the user's export selection.
//!
//! ## Why a library instead of one hard-coded profile
//!
//! The first cut of the 3MF writer emitted a single invented "Generic Printer /
//! 0.20mm Standard / Generic PLA" profile. That is enough to stop OrcaSlicer
//! showing empty spool cards, but it is not enough to make it recognise the
//! machine: the user still has to re-pick vendor, model, nozzle, process and
//! filament by hand after every export. Colour work done in CYM only pays off
//! if the file lands in the slicer already pointed at the right hardware.
//!
//! ## Where the data comes from
//!
//! `resources/presets/*.json` is generated by `tools/extract_orca_presets.py`
//! from an OrcaSlicer vendor profile tree. The generator walks the vendor index
//! (`profiles/<Vendor>.json`), which is the only whitelist that matters — the
//! profile directory also contains abandoned `... copy.json` / `..._old.json`
//! files, and at least one shipped preset carries a developer's leftover
//! `"printer_settings_id": "MyToolChanger 0.4 nozzle - Copy"`. The generator
//! resolves each preset against its `inherits` chain and then copies only a
//! field whitelist, which is what keeps that leftover out of our data.
//!
//! ## Why `include_str!` rather than a Tauri resource
//!
//! Shipping the JSON as a bundled resource means touching `tauri.conf.json`,
//! handling the dev/bundle path split, and dealing with a missing-file failure
//! mode at runtime. The library is 200 KB of static data that changes only when
//! we regenerate it, so compiling it in removes all three problems. When we add
//! "import your own profile" this module grows a second, fallible source; the
//! built-in one stays embedded.

use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};
use std::sync::OnceLock;

const SNAPMAKER_U1: &str = include_str!("../../resources/presets/snapmaker_u1.json");

/// One printer model, with every nozzle variant / process / filament the
/// vendor profile declares compatible with it.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MachinePreset {
    pub id: String,
    pub vendor: String,
    pub name: String,
    #[serde(default)]
    pub family: Option<String>,
    /// Slicer target -> the `printer_model_id` that target expects. Forks
    /// disagree: Snapmaker's own build registers the U1 as `SM_U1`, upstream
    /// OrcaSlicer as a numeric id.
    #[serde(default)]
    pub model_ids: Map<String, Value>,
    pub variants: Vec<MachineVariant>,
    pub processes: Vec<ProcessPreset>,
    pub filaments: Vec<FilamentPreset>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MachineVariant {
    pub nozzle_diameter: String,
    /// Exactly as the vendor index names it, e.g. `Snapmaker U1 (0.4 nozzle)`.
    /// The parenthesised form is load bearing: `compatible_printers` entries
    /// in the process and filament presets are matched against this string.
    pub preset_name: String,
    #[serde(default)]
    pub setting_id: Option<String>,
    pub config: Map<String, Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProcessPreset {
    pub name: String,
    #[serde(default)]
    pub setting_id: Option<String>,
    /// Nozzle diameters this process is offered for.
    pub nozzles: Vec<String>,
    #[serde(default)]
    pub layer_height: Option<String>,
    pub config: Map<String, Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FilamentPreset {
    pub name: String,
    #[serde(default)]
    pub setting_id: Option<String>,
    #[serde(default)]
    pub filament_id: Option<String>,
    pub nozzles: Vec<String>,
    /// `PLA`, `PETG`, ... Kept alongside `config.filament_type` because the UI
    /// groups by it and should not have to reach into the raw config.
    #[serde(rename = "type", default)]
    pub material: Option<String>,
    #[serde(default)]
    pub vendor: Option<String>,
    pub config: Map<String, Value>,
}

impl MachinePreset {
    pub fn variant(&self, nozzle: &str) -> Option<&MachineVariant> {
        self.variants.iter().find(|v| v.nozzle_diameter == nozzle)
    }

    pub fn process(&self, name: &str) -> Option<&ProcessPreset> {
        self.processes.iter().find(|p| p.name == name)
    }

    pub fn filament(&self, name: &str) -> Option<&FilamentPreset> {
        self.filaments.iter().find(|f| f.name == name)
    }

    /// `printer_model_id` for the requested slicer, falling back to any other
    /// target rather than emitting nothing — a wrong id is recoverable by the
    /// user, a missing one silently keeps the Generic Printer fallback.
    pub fn model_id_for(&self, target: &str) -> Option<&str> {
        self.model_ids
            .get(target)
            .and_then(Value::as_str)
            .or_else(|| self.model_ids.values().find_map(Value::as_str))
    }

    /// How many extruders the machine drives. Per-extruder options in the
    /// machine config are arrays whose length must match, so this is read off
    /// the data rather than assumed.
    pub fn extruder_count(&self, nozzle: &str) -> usize {
        self.variant(nozzle)
            .and_then(|v| v.config.get("nozzle_diameter"))
            .and_then(Value::as_array)
            .map(|a| a.len())
            .filter(|n| *n > 0)
            .unwrap_or(1)
    }
}

/// Everything the export dialog resolved. `None` anywhere means "the user did
/// not choose", and the writer falls back to its generic profile.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExportSelection {
    pub machine_id: String,
    pub nozzle_diameter: String,
    pub process_name: String,
    /// One filament preset name per extruder slot, in slot order. Shorter than
    /// the palette is allowed: remaining slots reuse the last entry, which is
    /// the common "same material, different colours" case.
    #[serde(default)]
    pub filament_names: Vec<String>,
    /// `orcaslicer` | `snapmaker_orca`. Decides which `printer_model_id` goes
    /// into the model metadata.
    #[serde(default = "default_target")]
    pub target_slicer: String,
}

fn default_target() -> String {
    "orcaslicer".to_string()
}

/// Selection resolved against the library, so the writer never has to deal
/// with a dangling name.
pub struct ResolvedSelection<'a> {
    pub machine: &'a MachinePreset,
    pub variant: &'a MachineVariant,
    pub process: &'a ProcessPreset,
    /// Exactly one entry per extruder slot requested.
    pub filaments: Vec<&'a FilamentPreset>,
    pub target_slicer: String,
}

impl ExportSelection {
    /// Resolve against the built-in library. Returns `Err` with a message the
    /// UI can show rather than silently degrading, because a mistyped machine
    /// id would otherwise produce a file that looks fine and slices wrong.
    pub fn resolve(&self, slot_count: usize) -> Result<ResolvedSelection<'static>, String> {
        let machine = library()
            .iter()
            .find(|m| m.id == self.machine_id)
            .ok_or_else(|| format!("unknown machine preset {:?}", self.machine_id))?;
        let variant = machine.variant(&self.nozzle_diameter).ok_or_else(|| {
            format!(
                "{} has no {} mm nozzle variant",
                machine.name, self.nozzle_diameter
            )
        })?;
        let process = machine
            .process(&self.process_name)
            .ok_or_else(|| format!("unknown process preset {:?}", self.process_name))?;

        let mut filaments = Vec::with_capacity(slot_count);
        for slot in 0..slot_count {
            // Fall back to the previous slot's choice, then to the first
            // filament compatible with this nozzle. A palette can have more
            // entries than the dialog offered pickers for.
            let name = self
                .filament_names
                .get(slot)
                .or_else(|| self.filament_names.last());
            let preset = match name {
                Some(n) => machine
                    .filament(n)
                    .ok_or_else(|| format!("unknown filament preset {:?}", n))?,
                None => machine
                    .filaments
                    .iter()
                    .find(|f| f.nozzles.iter().any(|n| n == &self.nozzle_diameter))
                    .ok_or_else(|| {
                        format!(
                            "{} ships no filament preset for the {} mm nozzle",
                            machine.name, self.nozzle_diameter
                        )
                    })?,
            };
            filaments.push(preset);
        }

        Ok(ResolvedSelection {
            machine,
            variant,
            process,
            filaments,
            target_slicer: self.target_slicer.clone(),
        })
    }
}

/// The embedded library. Parsed once; a parse failure is a build-time data
/// error, so it panics rather than degrading at runtime.
pub fn library() -> &'static [MachinePreset] {
    static LIB: OnceLock<Vec<MachinePreset>> = OnceLock::new();
    LIB.get_or_init(|| {
        vec![
            serde_json::from_str(SNAPMAKER_U1)
                .expect("resources/presets/snapmaker_u1.json is malformed"),
        ]
    })
}

// ---------------------------------------------------------------------------
// UI-facing summary
// ---------------------------------------------------------------------------
// The full library carries every preset's flattened config, ~200 KB. The
// dialog only needs names, so it gets a stripped view instead of paying that
// on every open.

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct MachineSummary {
    pub id: String,
    pub vendor: String,
    pub name: String,
    pub nozzles: Vec<String>,
    pub target_slicers: Vec<String>,
    pub processes: Vec<ProcessSummary>,
    pub filaments: Vec<FilamentSummary>,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ProcessSummary {
    pub name: String,
    pub nozzles: Vec<String>,
    pub layer_height: Option<String>,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct FilamentSummary {
    pub name: String,
    pub nozzles: Vec<String>,
    pub material: Option<String>,
    pub vendor: Option<String>,
}

pub fn summary() -> Vec<MachineSummary> {
    library()
        .iter()
        .map(|m| MachineSummary {
            id: m.id.clone(),
            vendor: m.vendor.clone(),
            name: m.name.clone(),
            nozzles: m.variants.iter().map(|v| v.nozzle_diameter.clone()).collect(),
            target_slicers: m.model_ids.keys().cloned().collect(),
            processes: m
                .processes
                .iter()
                .map(|p| ProcessSummary {
                    name: p.name.clone(),
                    nozzles: p.nozzles.clone(),
                    layer_height: p.layer_height.clone(),
                })
                .collect(),
            filaments: m
                .filaments
                .iter()
                .map(|f| FilamentSummary {
                    name: f.name.clone(),
                    nozzles: f.nozzles.clone(),
                    material: f.material.clone(),
                    vendor: f.vendor.clone(),
                })
                .collect(),
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn u1() -> &'static MachinePreset {
        library().iter().find(|m| m.id == "snapmaker_u1").unwrap()
    }

    #[test]
    fn the_embedded_library_parses() {
        assert!(!library().is_empty());
    }

    #[test]
    fn the_u1_declares_all_four_nozzle_variants() {
        let nozzles: Vec<&str> = u1()
            .variants
            .iter()
            .map(|v| v.nozzle_diameter.as_str())
            .collect();
        assert_eq!(nozzles, ["0.2", "0.4", "0.6", "0.8"]);
    }

    #[test]
    fn variant_preset_names_keep_the_parenthesised_form() {
        // `compatible_printers` in the process/filament presets is matched
        // against this exact string; dropping the brackets breaks the join.
        assert_eq!(
            u1().variant("0.4").unwrap().preset_name,
            "Snapmaker U1 (0.4 nozzle)"
        );
    }

    #[test]
    fn the_u1_is_a_four_extruder_toolchanger() {
        // Per-extruder machine options are arrays and OrcaSlicer rejects a
        // length mismatch, so this count is a contract with the writer.
        assert_eq!(u1().extruder_count("0.4"), 4);
    }

    #[test]
    fn no_leftover_developer_settings_id_survived_extraction() {
        let raw = SNAPMAKER_U1;
        assert!(
            !raw.contains("MyToolChanger"),
            "the mainline U1 variant carries a stale copied printer_settings_id \
             that must not ship"
        );
    }

    #[test]
    fn both_slicer_targets_have_a_model_id() {
        assert_eq!(u1().model_id_for("snapmaker_orca"), Some("SM_U1"));
        assert_eq!(u1().model_id_for("orcaslicer"), Some("797581801"));
    }

    #[test]
    fn an_unknown_target_falls_back_rather_than_emitting_nothing() {
        assert!(u1().model_id_for("prusaslicer").is_some());
    }

    #[test]
    fn every_process_and_filament_maps_onto_a_real_variant() {
        let known: Vec<&str> = u1()
            .variants
            .iter()
            .map(|v| v.nozzle_diameter.as_str())
            .collect();
        for p in &u1().processes {
            assert!(!p.nozzles.is_empty(), "{} lists no nozzle", p.name);
            for n in &p.nozzles {
                assert!(known.contains(&n.as_str()), "{} -> unknown nozzle {}", p.name, n);
            }
        }
        for f in &u1().filaments {
            assert!(!f.nozzles.is_empty(), "{} lists no nozzle", f.name);
        }
    }

    #[test]
    fn resolving_a_selection_fills_every_slot() {
        let sel = ExportSelection {
            machine_id: "snapmaker_u1".into(),
            nozzle_diameter: "0.4".into(),
            process_name: "0.20 Standard @Snapmaker U1 (0.4 nozzle)".into(),
            filament_names: vec!["Generic PLA".into()],
            target_slicer: "orcaslicer".into(),
        };
        let resolved = sel.resolve(6).expect("must resolve");
        assert_eq!(resolved.filaments.len(), 6);
        // One picker, six slots: the last choice repeats.
        assert!(resolved.filaments.iter().all(|f| f.name == "Generic PLA"));
    }

    #[test]
    fn a_selection_can_mix_materials_per_slot() {
        let sel = ExportSelection {
            machine_id: "snapmaker_u1".into(),
            nozzle_diameter: "0.4".into(),
            process_name: "0.20 Standard @Snapmaker U1 (0.4 nozzle)".into(),
            filament_names: vec!["Generic PLA".into(), "Generic PETG".into()],
            target_slicer: "orcaslicer".into(),
        };
        let resolved = sel.resolve(2).expect("must resolve");
        assert_eq!(resolved.filaments[0].material.as_deref(), Some("PLA"));
        assert_eq!(resolved.filaments[1].material.as_deref(), Some("PETG"));
    }

    #[test]
    fn a_dangling_name_is_an_error_not_a_silent_fallback() {
        let sel = ExportSelection {
            machine_id: "snapmaker_u1".into(),
            nozzle_diameter: "0.4".into(),
            process_name: "no such process".into(),
            filament_names: vec![],
            target_slicer: "orcaslicer".into(),
        };
        assert!(sel.resolve(1).is_err());
    }

    #[test]
    fn the_summary_drops_the_config_payload() {
        let s = summary();
        let json = serde_json::to_string(&s).unwrap();
        assert!(!json.contains("printable_area"));
        assert!(json.len() < SNAPMAKER_U1.len() / 4, "summary must be far smaller");
    }
}
